In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [4]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [5]:
test=pd.read_csv('/content/drive/My Drive/test.csv')

In [7]:
train=pd.read_csv('/content/drive/My Drive/train.csv')

In [8]:
train = train[['target','comment_text']]
train.head()

target                                       comment_text
0  0.000000  This is so cool. It's like, 'would you want yo...
1  0.000000  Thank you!! This would make my life a lot less...
2  0.000000  This is such an urgent design problem; kudos t...
3  0.000000  Is this something I'll be able to install on m...
4  0.893617               haha you guys are a bunch of losers.

In [9]:
x = train['comment_text'].tolist()
x[:5]

["This is so cool. It's like, 'would you want your mother to read this??' Really great idea, well done!",
 "Thank you!! This would make my life a lot less anxiety-inducing. Keep it up, and don't let anyone get in your way!",
 'This is such an urgent design problem; kudos to you for taking it on. Very impressive!',
 "Is this something I'll be able to install on my site? When will you be releasing it?",
 'haha you guys are a bunch of losers.']

In [10]:
y = train['target'].tolist()
y

[0.0,
 0.0,
 0.0,
 0.0,
 0.8936170212765957,
 0.6666666666666666,
 0.4576271186440678,
 0.0,
 0.0,
 0.0,
 0.0,
 0.44,
 0.0,
 0.6,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.9125,
 0.0,
 0.0,
 0.8307692307692307,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.2,
 0.0,
 0.2,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3,
 0.3611111111111111,
 0.0,
 0.0,
 0.3,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.4,
 0.4,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.6,
 0.0,
 0.0,
 0.0,
 0.0,
 0.16666666666666666,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.7,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,

In [11]:
from keras.preprocessing.text import text_to_word_sequence
from keras.preprocessing.text import Tokenizer  
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import LSTM, Bidirectional, GRU, Dropout,Embedding ,Dense
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [12]:
vocab_sz = 10000
maxlen=100
x_train, x_test, y_train, y_test = train_test_split(x[:60000], y[:60000], test_size=0.3, random_state=42)
tok = Tokenizer(num_words=vocab_sz, oov_token='UNK')
tok.fit_on_texts(x)
x_train = tok.texts_to_sequences(x_train)
x_test = tok.texts_to_sequences(x_test )
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test = pad_sequences(x_test, maxlen=maxlen)

In [13]:
model = Sequential()
model.add(Embedding(vocab_sz+1, 50, input_length=maxlen))
model.add(LSTM(128))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 50)           500050    
_________________________________________________________________
lstm (LSTM)                  (None, 128)               91648     
_________________________________________________________________
dense (Dense)                (None, 1)                 129       
Total params: 591,827
Trainable params: 591,827
Non-trainable params: 0
_________________________________________________________________


In [14]:
y_train= np.array (y_train)
y_test= np.array(y_test)

In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train, y_train,batch_size=64, epochs=10
          ,validation_data=(x_test, y_test))

Epoch 1/10
657/657 [==============================] - 121s 155ms/step - loss: 0.3128 - accuracy: 0.7380 - val_loss: 0.2446 - val_accuracy: 0.7425
Epoch 2/10
657/657 [==============================] - 98s 150ms/step - loss: 0.2336 - accuracy: 0.7403 - val_loss: 0.2317 - val_accuracy: 0.7423
Epoch 3/10
657/657 [==============================] - 98s 150ms/step - loss: 0.2193 - accuracy: 0.7416 - val_loss: 0.2276 - val_accuracy: 0.7427
Epoch 4/10
657/657 [==============================] - 97s 148ms/step - loss: 0.2108 - accuracy: 0.7419 - val_loss: 0.2341 - val_accuracy: 0.7411
Epoch 5/10
657/657 [==============================] - 97s 147ms/step - loss: 0.2045 - accuracy: 0.7448 - val_loss: 0.2351 - val_accuracy: 0.7429
Epoch 6/10
657/657 [==============================] - 96s 147ms/step - loss: 0.2002 - accuracy: 0.7433 - val_loss: 0.2381 - val_accuracy: 0.7427
Epoch 7/10
657/657 [==============================] - 96s 146ms/step - loss: 0.1926 - accuracy: 0.7431 - val_loss: 0.2468 - val_a

In [16]:
test= test['comment_text']
test.head()

0    [ Integrity means that you pay your debts.]\n\...
1    This is malfeasance by the Administrator and t...
2    @Rmiller101 - Spoken like a true elitist. But ...
3    Paul: Thank you for your kind words.  I do, in...
4    Sorry you missed high school. Eisenhower sent ...
Name: comment_text, dtype: object

In [46]:
xt = test.tolist()
xt[:5]

['[ Integrity means that you pay your debts.]\n\nDoes this apply to President Trump too?',
 'This is malfeasance by the Administrator and the Board.  They are wasting our money!',
 '@Rmiller101 - Spoken like a true elitist. But look out bud. The re-awakening in Europe, Brexit and now the Trump victory are just the beginning. The unwashed masses are coming for you and your ilk….',
 'Paul: Thank you for your kind words.  I do, indeed, have strong beliefs and don\'t hide them.  They are based on both facts and values.  I think the question of "bias" and "prejudice" comes into play when we\'re discussing beliefs and attitudes based on values.  One of our poster friends,  for example, often comments that being "intolerant" of a bias, for example, is, in itself, a bias.  This is, IMO, where the concept of "irratonal antipathy" is important.  If I dislike neo-Nazis because of their views on race, my antipathy is based on fact (knowledge of their views) and values (my belief that condemning ot

In [47]:
vocab_sz = 10000
maxlen=100
tok = Tokenizer(num_words=vocab_sz, oov_token='UNK') #oov_token replace any unknown words with a token of our choosing
tok.fit_on_texts(xt)
xt = tok.texts_to_sequences(xt)
xt = pad_sequences(xt, maxlen=maxlen) #to ensure all the sequences to have same length
print(xt)

[[   0    0    0 ...  154   54  118]
 [   0    0    0 ... 2687   57  100]
 [   0    0    0 ...    4   37    1]
 ...
 [   0    0    0 ...    1    8  899]
 [   0    0    0 ...    6   79  165]
 [   0    0    0 ...  112   12  268]]


In [19]:
y_pred= model.predict(xt)

In [23]:
y_pred = np.where(y_pred>=0.5,1.,0.)
submission = pd.read_csv('/content/drive/My Drive/sample_submission_second.csv')
submission['prediction'] = y_pred
#submission_df.to_csv('submission.csv',index = False)
submission.head()


id  prediction
0  7097320         0.0
1  7097321         0.0
2  7097322         0.0
3  7097323         0.0
4  7097324         0.0

In [32]:

from google.colab import files
submission.to_csv('toxicity.csv',index=False)
df = pd.read_csv ('toxicity.csv')
print(df)
df.describe()
files.download('toxicity.csv')


            id  prediction
0      7097320         0.0
1      7097321         0.0
2      7097322         0.0
3      7097323         0.0
4      7097324         0.0
...        ...         ...
97315  7194635         0.0
97316  7194636         0.0
97317  7194637         0.0
97318  7194638         0.0
97319  7194639         0.0

[97320 rows x 2 columns]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>